# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Devesh Sangwan"
subtitle: "See the world through my eyes!"
author:  "Devesh Sangwan"
header:
 title: "Photography"
 subtitle: "by Devesh Sangwan"
footer:
 name: "Hey there, I am Devesh Sangwan "
 bio: "a pre-final year computer engineering student at the Netaji Subhas University of Technology, New Delhi."
social_urls:
  twitter: "https://twitter.com/sangwan2001"
  instagram: "https://www.instagram.com/devesh.sangwan/"
  linkedin: "https://www.linkedin.com/in/devesh-sangwan-4a6646165/"
  github: "https://github.com/deveshsangwan"
